module.exports = [{
  'songname': '作者介绍、朗读者介绍',
  'enworkid': '/s/zMJoBsEtQWaw8zZigcsrjA',
  'src': 'https://media.alearning.com.cn/podcast/book/2/201.mp3',
  'type': 'MP3'
}, {
  'songname': '交流密码：我说的你听懂了吗？（3--6岁）',
  'enworkid': '/s/tbDgGfP4KLhVS_H9c0xjoA',
  'src': 'https://media.alearning.com.cn/podcast/book/2/202.mp3',
  'type': 'MP3'
}, {
  'songname': '交流密码：我说的你听懂了吗？（7--12岁）',
  'enworkid': '/s/nj0hndV7qXICtcA-OSbkUQ',
  'src': 'https://media.alearning.com.cn/podcast/book/2/203.mp3',
  'type': 'MP3'
}, {
  'songname': '令人满意和令人不快的称赞',
  'enworkid': '/s/xRkKN0oFne4wAXuQj5Abyw',
  'src': 'https://media.alearning.com.cn/podcast/book/2/204.mp3',
  'type': 'MP3'
}, {
  'songname': '无效沟通，有效沟通',
  'enworkid': '/s/xRkKN0oFne4wAXuQj5Abyw',
  'src': 'https://media.alearning.com.cn/podcast/book/2/205.mp3',
  'type': 'MP3'
}, {
  'songname': '学会称赞',
  'enworkid': '/s/xRkKN0oFne4wAXuQj5Abyw',
  'src': 'https://media.alearning.com.cn/podcast/book/2/206.mp3',
  'type': 'MP3'
}, {
  'songname': '找到更好的解决方法',
  'enworkid': '/s/xRkKN0oFne4wAXuQj5Abyw',
  'src': 'https://media.alearning.com.cn/podcast/book/2/207.mp3',
  'type': 'MP3'
}]
